# Generated by Django 3.1.6 on 2021-02-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=100)),
                ('ProjectName', models.EmailField(max_length=254)),
                ('Type', models.CharField(max_length=100)),
                ('GraduationYear', models.CharField(max_length=20)),
                ('Abstract', models.CharField(max_length=1000)),
                ('Keyword', models.CharField(max_length=20)),
                ('Technology', models.CharField(max_length=20)),
                ('Award', models.CharField(max_length=20)),
                ('LinkGit', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'dataproject',
            },
        ),
    ]
